version: '3.8'
services:
  kardo-db:
    image: postgres:14-alpine
    container_name: kardo_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=kardo-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  kardo-service:
    build: ./kardo-service/kardo-service-server
    image: kardo-service
    container_name: kardo_service_container
    ports:
      - "9090:9090"
    depends_on:
      - kardo-db
    environment:
      - DB_HOST=kardo-db
      - DB_PORT=5432
      - DB_NAME=kardo-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  kardo-gateway:
    build: ./kardo-gateway/
    image: kardo-gateway
    container_name: kardo_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - kardo-service
    environment:
      - KARDO_SERVICE_URL=http://kardo-service:9090