-- создаём таблицу users (с пользователями):
CREATE TABLE IF NOT EXISTS users(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50),
    patronymic varchar(50),
    birthday date,
    sex varchar(6),
    email varchar(254) NOT NULL,
    phone varchar(20),
    social_link varchar(200),
    country varchar(50),
    region varchar(50),
    city varchar(50),
    portfolio_link varchar(200),
    about_user varchar(5000),
    password varchar(50) NOT NULL,
    registration_date timestamp NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);